### ISSUE TITLE
Curl not installed or enabled in php.ini\nMbstring extension not enabled.

### ISSUE THREAD

**Issue by Shahul11** [sumeetweb/Thinki-Downloader#10]
All though I have removed the semicoln  from  curl 
extension=curl
extension=mbstring
extension=openssl

Still it gives me the error as follows

PHP Warning:  PHP Startup: Unable to load dynamic library 'curl' (tried: C:\php\ext\curl (The specified module could not be found.), C:\php\ext\php_curl.dll (The specified module could not be found.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'curl' (tried: C:\php\ext\curl (The specified module could not be found.), C:\php\ext\php_curl.dll (The specified module could not be found.)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring' (tried: C:\php\ext\mbstring (The specified module could not be found.), C:\php\ext\php_mbstring.dll (The specified module could not be found.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'mbstring' (tried: C:\php\ext\mbstring (The specified module could not be found.), C:\php\ext\php_mbstring.dll (The specified module could not be found.)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl' (tried: C:\php\ext\openssl (The specified module could not be found.), C:\php\ext\php_openssl.dll (The specified module could not be found.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'openssl' (tried: C:\php\ext\openssl (The specified module could not be found.), C:\php\ext\php_openssl.dll (The specified module could not be found.)) in Unknown on line 0
\nCurl not installed or enabled in php.ini\nMbstring extension not enabled. Remove ; from php.ini config in the line ;extension=mbstring\nOpenssl not enabled in php.ini
C:\Users\RRR\Downloads\Thinki-Downloader-main>

**Comment by sumeetweb** [comment]
I think there's an issue with PHP installation. Can you try installing Laragon (https://laragon.org/) instead and then try running the script again.

Best, 
Sumeet

**Comment by Shahul11** [comment]
it worked I fixed stuck with another problem starts downloading then this happens
![image](https://user-images.githubusercontent.com/25701505/130494218-a09e9fc2-a016-4346-8dfd-571121829997.png)

**Comment by Shahul11** [comment]
![image](https://user-images.githubusercontent.com/25701505/130494288-9901dbfa-b7b0-4dd6-bfa2-7ccf15bd4d97.png)

**Comment by Shahul11** [comment]
it does not download

**Comment by sumeetweb** [comment]
> ![image](https://user-images.githubusercontent.com/25701505/130494288-9901dbfa-b7b0-4dd6-bfa2-7ccf15bd4d97.png)
> 
> it just stops and comes back cmd prompt

There's wrong format of link being used.

https://title.thinkific.com/api/course_player/v2/courses/course-name

Try finding url of this pattern, having v2/courses/

**Comment by Shahul11** [comment]
![image](https://user-images.githubusercontent.com/25701505/130496183-74019f2f-b754-4493-a169-234c7418cc1d.png)

you can se the complete URL , I have updated the right cookie for the above URL and the  x-thinkific-client-date:   I just observed i dont have vistor id

**Comment by VermaPriyansh** [comment]
I am having the same problem, even though, my site has /courses/ in the URL. I have attached a screenshot below.
![image](https://user-images.githubusercontent.com/6913665/133955692-8c8b58de-246f-4e63-b5ea-f47c1d5c2895.png)

**Comment by roadparc** [comment]
> All though I have removed the semicoln from curl
> extension=curl
> extension=mbstring
> extension=openssl
> 
> Still it gives me the error as follows
> 
> PHP Warning: PHP Startup: Unable to load dynamic library 'curl' (tried: C:\php\ext\curl (The specified module could not be found.), C:\php\ext\php_curl.dll (The specified module could not be found.)) in Unknown on line 0
> 
> Warning: PHP Startup: Unable to load dynamic library 'curl' (tried: C:\php\ext\curl (The specified module could not be found.), C:\php\ext\php_curl.dll (The specified module could not be found.)) in Unknown on line 0
> PHP Warning: PHP Startup: Unable to load dynamic library 'mbstring' (tried: C:\php\ext\mbstring (The specified module could not be found.), C:\php\ext\php_mbstring.dll (The specified module could not be found.)) in Unknown on line 0
> 
> Warning: PHP Startup: Unable to load dynamic library 'mbstring' (tried: C:\php\ext\mbstring (The specified module could not be found.), C:\php\ext\php_mbstring.dll (The specified module could not be found.)) in Unknown on line 0
> PHP Warning: PHP Startup: Unable to load dynamic library 'openssl' (tried: C:\php\ext\openssl (The specified module could not be found.), C:\php\ext\php_openssl.dll (The specified module could not be found.)) in Unknown on line 0
> 
> Warning: PHP Startup: Unable to load dynamic library 'openssl' (tried: C:\php\ext\openssl (The specified module could not be found.), C:\php\ext\php_openssl.dll (The specified module could not be found.)) in Unknown on line 0
> \nCurl not installed or enabled in php.ini\nMbstring extension not enabled. Remove ; from php.ini config in the line ;extension=mbstring\nOpenssl not enabled in php.ini
> C:\Users\RRR\Downloads\Thinki-Downloader-main>

I found the same issue with PHP and the solution is to find the following line in your php.ini file (on mine was line 760):
; On windows:
; extension_dir = "ext"
and remove the ";" from the begining of the line ; extension_dir = "ext"

So your PHP.ini should look like this:
; On windows:
extension_dir = "ext"

The PHP.INI template comes with that lines disable, and the first time you are going to use extensions, you have to uncomment thouse lines depending on your OS.

RP
uncomment the line

**Comment by roadparc** [comment]
> ![image](https://user-images.githubusercontent.com/25701505/130496183-74019f2f-b754-4493-a169-234c7418cc1d.png)
> 
> you can se the complete URL , I have updated the right cookie for the above URL and the x-thinkific-client-date: I just observed i don't have vistor id
> 
> ![image](https://user-images.githubusercontent.com/25701505/130496375-5001b43c-3ae7-4082-988b-d90ab63f47f0.png)

Same for me. The script just exists without downloading anything.
I also notice that my cookie is missing the client ID.
Where else can we find the client ID?

**Comment by sumeetweb** [comment]
This errors are happening due to missing dll files. Editing the php.ini will not solve the problem. Please use any preconfigured stack like Laragon (https://laragon.org/) to avoid these issues.
