### ISSUE TITLE
Script just exits

### ISSUE THREAD

**Issue by arunfiddler** [sumeetweb/Thinki-Downloader#11]
When i tried to download the content its coming like 
![image](https://user-images.githubusercontent.com/29367030/131335622-069ee00d-b73a-49ae-a3b7-505993431db5.png)
 Are there any other way?

**Comment by sumeetweb** [comment]
There's some error with session id and client date probably. Can you share the generated json file?

**Comment by chessboards** [comment]
I'm having the same issue. I set my log file in php.ini to `error_log = "./php_errors.log"` but no logfile gets created. Maybe retrying the cookie/date will work better..

**Comment by chessboards** [comment]
No luck. I tried using chrome's network analyzer- copying the request cookie and course client id only generates a json file and nothing else.

**Comment by chessboards** [comment]
![image](https://user-images.githubusercontent.com/64972947/143452225-ddcdb92e-dbac-426c-a980-ed8799657339.png)
It also seems that these cases are empty..

**Comment by sumeetweb** [comment]
> 

Currently, I don't have an account returning those cases. I will work on them once I get hold of an account.

**Comment by sumeetweb** [comment]
https://github.com/sumeetweb/Thinki-Downloader/issues/5
