### ISSUE TITLE
Course Folders & Sub Folders generated but no content

### ISSUE THREAD

**Issue by tradigital1** [sumeetweb/Thinki-Downloader#12]
Able to generate folders and sub folder but not the videos.  

Checked out a solution in other issue thread  #5  regarding display name but could not make it work.  

Tried with two different courses one with basic video and no other downloads and the other with quizzes, notes, signup for webinars along with videos and pdf.   

In that one the  webinar sign up screen with a text link downloads as a blank html page but nothing else.

Any suggestions or able to point me in a direction to look to solve?

**Comment by drduker** [comment]
multimedia pages type aren't downloaded.  Just Text,Video download for me.

**Comment by drduker** [comment]
I created this function and it grabs the multimedia types as well:

```
                if($content["default_lesson_type_label"] == "Multimedia" && $content["default_lesson_type_icon"] == "multimedia") //For Downloading Notes which are in HTML Unicode Format
		        {
                    $dc = $index.'. '.$content["name"].' Multimedia';
                    $dc = filter_filename($dc);
                    mkdir($dc, 0777);
                    $prev_dir = getcwd();
                    chdir($dc);
                    echo "Downloading ".$content["name"].PHP_EOL;
                    $result = query("https://".$p['host']."/api/course_player/v2/iframes/".$content['contentable']);
                    $temp = json_decode($result,true);
                    $temp2 = unicode_decode($temp["iframe"]["source_url"]); //Store Unicode Decoded HTML Code to temp2
                    echo $temp2;
                    $file_contents = file_get_contents($temp2);
                    $fname = $content["name"].".html";
                    $myfile = fopen($fname, "w");
                    fwrite($myfile, $file_contents);
                    fclose($myfile);
                    chdir($prev_dir);
                }
               ```

**Comment by drduker** [comment]
Added MR/PR here: https://github.com/sumeetweb/Thinki-Downloader/pull/13

**Comment by sumeetweb** [comment]
Are you using windows @tradigital1?

https://github.com/sumeetweb/Thinki-Downloader/issues/5#issuecomment-984973362

**Comment by sumeetweb** [comment]
@drduker Added support to download quiz with their answers . Can you review it once when idle?

**Comment by tradigital1** [comment]
Yes using windows 10 and also tried @drduker but it still didn't bring down the content.  Just the folders and sub-folders.

**Comment by sumeetweb** [comment]
Can you share the json file generated?

**Comment by tradigital1** [comment]
I sent it to you - did you receive it?

**Comment by sumeetweb** [comment]
Where have you sent? Haven't received any mail.

**Comment by tradigital1** [comment]
I sent to onhax@protonmail.com

**Comment by sumeetweb** [comment]
Thanks @tradigital1. The json is alright. Windows is having some problem with curl. Can you please try to check it once in Linux?
