### ISSUE TITLE
Download the files to another directory (e.g : external drive)

### ISSUE THREAD

**Issue by satolas** [sumeetweb/Thinki-Downloader#16]
Hello :-)
Awesome little tool ! It seems to work so far.

I would like to download the website on an external drive (my local C drive is almost full).
For that course there is a lot of videos to download so it would be nice to know where is the export path.
Maybe would be nice to make it available in config.php ?

Cheers, and thanks a lot for your super nice tool :-)

**Comment by sumeetweb** [comment]
You can run the script in the drive you want to download. It will download files into your terminal's current directory where the script resides.

**Comment by satolas** [comment]
Thanks a lot for your answer :-) That was fast.

For me so far it's downloading into the php folder (in my case : C:\xampp\php)
And the script (config file, thinkidownloader.php etc...) are in c:\downloader.

Maybe in the command line I could change the path ?
I'm not sure moving the script will change the download path.
Because the script is currently not in the php folder, but anyways downloaded there.

Cheers

**Comment by sumeetweb** [comment]
I got the issue. I will try adding a path variable into it in next push.

Best,
Sumeet.

**Comment by sumeetweb** [comment]
> Thanks a lot for your answer :-) That was fast.
> 
> For me so far it's downloading into the php folder (in my case : C:\xampp\php)
> And the script (config file, thinkidownloader.php etc...) are in c:\downloader.
> 
> Maybe in the command line I could change the path ?
> I'm not sure moving the script will change the download path.
> Because the script is currently not in the php folder, but anyways downloaded there.
> 
> Cheers
> 
> EDIT : just tried, indeed it is still downloading in the same location (C:\xampp\php)

Just a question, is it creating the whole course folder inside xampp/php folder?

**Comment by satolas** [comment]
Sorry I dindn't see your question.
Yes exactly :-)
Main folder of the whole course and the json file are downloaded in C:/xampp/php

**Comment by sumeetweb** [comment]
> Sorry I dindn't see your question. Yes exactly :-) Main folder of the whole course and the json file are downloaded in C:/xampp/php
> 
> What I do in the CMD : 1)cd C:\xampp\php 2) php C:\downloader\thinkidownloader3.php https://courseadress.com/course

Does your php doesn't work outside "C:/xampp/php" directory? If yes, then you need to set environment variables in windows.
