### ISSUE TITLE
Tool Looks Great ! but facing issue while configuring

### ISSUE THREAD

**Issue by CK0411** [sumeetweb/Thinki-Downloader#18]
Hey Sumeet,

Nice to see you contribution for community.
I am trying to configure this tool like below.
1. Downloaded PHP v7.4.1
2. Edited PHP.INI(Deployment) PHP.INI(Production) File and remove ; from curl,openssl;, mbstring  extension
3. Added PHP path to environment variable.
4. finally tried to execute the command but face below issue.
\nCurl not installed or enabled in php.ini\nMbstring extension not enabled. Remove ; from php.ini config in the line ;extension=mbstring\nOpenssl not enabled in php.ini

Even I tried to used XAMPP PHP but still same issue getting. Can you please help me here ?

**Comment by sumeetweb** [comment]
Maybe there's issue with environment variables.
