### ISSUE TITLE
Cloudflare protected site

### ISSUE THREAD

**Issue by Fanan90** [sumeetweb/Thinki-Downloader#19]
HI.
I'm getting stuck on a Cloudflare protected site, when I try to run the script, the json generated is the code of an Cloudflare "Sorry, you have been blocked" page. There is some way to dodge it?
Thanks in advance.

**Comment by sumeetweb** [comment]
Hello @Fanan90

You can try using a VPN to bypass CF's restriction.

**Comment by sumeetweb** [comment]
Send me the site link in my mail, onhax@protonmail.com. 
I'll check it up, if it's blocked here too or any script error.

**Comment by sumeetweb** [comment]
Hello @Fanan90. The files are downloadable at my end. There seems to be ISP issue at your end.
