### ISSUE TITLE
Only downloading one chapter

### ISSUE THREAD

**Issue by tiagocborg** [sumeetweb/Thinki-Downloader#20]
I was able to set it up, thanks for that.

Although, the course is split into chapters, and it will only download the first chapters. I can see on the json object that all the chapters are there, but only the first is being downloaded 

Any idea?

**Comment by sumeetweb** [comment]
Hello, @tiagocborg. Thanks for trying out the script. It will be helpful to debug if you can share the .json file generated by script.

**Comment by tiagocborg** [comment]
@sumeetweb hello, 

Nevermind that, I found the issue. Turns out a `/` on the name of the chapter was breaking the download. Replacing it with a underscore fixed the issue.
