### ISSUE TITLE
PDF not supported?

### ISSUE THREAD

**Issue by herminian** [sumeetweb/Thinki-Downloader#21]
The script has worked for me so far, thank you very much. However, folders for chapters that contain solely pdf files are completely empty. Is there any way I can download the pdf files, or is it currently not supported at all?

**Comment by sumeetweb** [comment]
Hello, @herminian. Thanks for trying out the script.

PDF downloading are supported in Thinki-Downloader. It will be helpful to debug if you can share the .json file generated by script.

**Comment by herminian** [comment]
Thanks for your reply. I have sent the .json file to your email. Have you received it?

**Comment by sumeetweb** [comment]
Hi, there. Just pushed PDF Downloads. Please check.

**Comment by maqeelqureshi** [comment]
Generating Pdf files with 0 size.

**Comment by sumeetweb** [comment]
Send course json dumps for evaluating it.

**Comment by maqeelqureshi** [comment]
I tried on another machine, it's working fine. Thanks
