### ISSUE TITLE
Choosing video quality

### ISSUE THREAD

**Issue by karlpratchett** [sumeetweb/Thinki-Downloader#22]
Thanks for the great tool it's working well apart from the videos been downloaded being extremely large as it downloads the videos in the highest possible quality.  Is there anyway to limit the resolution or quality of the videos so I can fit it on my harddrive?  Different resolutions of the educational videos seem to be hosted as I can choose which one to download off the course site using this chrome extension. https://chrome.google.com/webstore/detail/wistia-video-downloader/acbiaofoeebeinacmcknopaikmecdehl?hl=en

**Comment by sumeetweb** [comment]
Thanks for suggestion. I need to check how this quality checking works in the extension. 

In my enrolled courses, I don't had quality selector, so I gone the default way.

Best,
Sumeet.
