### ISSUE TITLE
Individual video downloads

### ISSUE THREAD

**Issue by geometrus-crypto** [sumeetweb/Thinki-Downloader#23]
Would it be possible to support individual downloads? I have a course that releases new videos each week but then removes them after 5-14 days. It would be nice to be able to get them 1 at a time to avoid re-downloading many previous videos just to ensure I get the new ones.

Additionally, it seems useful to be able to download specific videos rather than an entire course if you only are interested in a few of the concepts.

Thanks!

**Comment by sumeetweb** [comment]
Yes. It's a nice idea. We can implement it. Need some time for that though.

**Comment by sumeetweb** [comment]
> . It would be nice to be able to get them 1 at a time to avoid re-downloading many previous videos just to ensure I get the new ones.

It's possible to add checks to `SKIP` already downloaded files from the list and then you can re-run script again to get the new or missing ones.

**Comment by AlienFever** [comment]
> > . It would be nice to be able to get them 1 at a time to avoid re-downloading many previous videos just to ensure I get the new ones.
> 
> It's possible to add checks to `SKIP` already downloaded files from the list and then you can re-run script again to get the new or missing ones.

Has this feature been implemented yet ?
Thanks!

**Comment by sumeetweb** [comment]
> > > . It would be nice to be able to get them 1 at a time to avoid re-downloading many previous videos just to ensure I get the new ones.
> > 
> > 
> > It's possible to add checks to `SKIP` already downloaded files from the list and then you can re-run script again to get the new or missing ones.
> 
> Has this feature been implemented yet ? Thanks!

Individual file downloading hasn't been implemented yet, but it's does SKIPs already downloaded files. So, you can restart the script anytime. It prints the downloading logs but skips those files. 

I am yet to figure out a process to let user select which files to download. I don't have much experience building CLI tools, but I am thinking to create a website, where user can select the files by uploading the course json file which the script generates and user can modify it on the website and redownload and pass it to the script to download. 

Any thoughts?

**Comment by AlienFever** [comment]
Yeah I was asking about the skip function, thanks for implementing that!
The website seems like a good idea tbh, it is a simple solution at least until you decide if this will be online or a GUI.

**Comment by Gentleman03** [comment]
GUI would be awesome. I also need sometimes to download one new video from whole course so it would be nice to have such possibility. 

@sumeetweb Any plans on adding feature to download discussions? 

BTW. Thank you very much for sharing this utility <3

**Comment by sumeetweb** [comment]
Hello @Gentleman03. I took this weekend to figure this out and created a experimental JSON editor. I am somewhat noob in Frontend XD. Hope to finish it up this week.

https://sumeetweb.github.io/Thinki-Parser/

Thanks for using the script. 😁

**Comment by sumeetweb** [comment]
I will plan for adding discussions. 👍

**Comment by Gentleman03** [comment]
>Hello @Gentleman03. I took this weekend to figure this out and created a experimental JSON editor. I am somewhat noob in >Frontend XD. Hope to finish it up this week.

>Link for Thinki-Parser:
>https://sumeetweb.github.io/Thinki-Parser/

>Link to Thinki-Downloader Experimental Branch:
>https://github.com/sumeetweb/Thinki-Downloader/tree/json-file

>Thanks for using the script. 😁

---
> I will plan for adding discussions.

Thank you very much. BTW. Have you noticed that your script doesn't download audio files? It also doesn't download attached files from pages where you have text and then attached files a the bottom of the page.

**Comment by sumeetweb** [comment]
Oh, I didn't knew about this issue. Thanks for reporting @Gentleman03 . Need to check with a sample account.

**Comment by Gentleman03** [comment]
> Oh, I didn't knew about this issue. Thanks for reporting @Gentleman03 . Need to check with a sample account.

My pleasure. Glad to help :)
