### ISSUE TITLE
Create docker image

### ISSUE THREAD

**Issue by saspelo** [sumeetweb/Thinki-Downloader#24]
what about create docker image with this program? I d'int want to install all php stuff....

**Comment by sumeetweb** [comment]
I don't have much experience working with docker containers. You can try creating one.

**Comment by sumeetweb** [comment]
I was experimenting Docker today. 
Created a docker compose file and some minor changes.

https://github.com/sumeetweb/Thinki-Downloader/tree/add-docker-support
