### ISSUE TITLE
Changed url pattern leads to Internal Server Error

### ISSUE THREAD

**Issue by himanshubabal** [sumeetweb/Thinki-Downloader#26]
Earlier url - https://URL-OF-WEBSITE/api/course_player/v2/courses/COURSE-NAME-SLUG
Newer - https://URL-OF-WEBSITE/api/course_player/v2/enrollments?course_slug=COURSE-NAME-SLUG

Using the earlier pattern yields `{"error":"Authentication Error"}` in the browser and `Internal Server Error` in the script terminal.

**Comment by sumeetweb** [comment]
You're using wrong URL to fetch the course contents.

Select the slug in Fetch/XHR Request in Network Tab. Then Copy Request URL from General section and Cookie data and X Client date from Request Header section.

![image](https://user-images.githubusercontent.com/25149022/184542107-e6ec395e-7a9b-429f-9d18-566c1d2325ab.png)
