### ISSUE TITLE
Endoding problems

### ISSUE THREAD

**Issue by felagund** [sumeetweb/Thinki-Downloader#29]
Hello, I think I am running to similar problems as in this bug: https://github.com/sumeetweb/Thinki-Downloader/issues/8

My course has non asci characters in it and it seems to be causing problems:

When I try to download the course, it says `Downloading Návod ke kurzu Začínáme cvičit`.

However, the  folder created is named "Zač�-náme cvičit" (it should have been "í"; I cannot browse it with Dolphin).

When in `include/file.functions.php` I move `return $filename;` above the ` $filename = preg_replace(` line, the issue disappears (I found it out by putting `echo statements after each statement in the function `filter_filename(`)

**Comment by sumeetweb** [comment]
Hi, @felagund. Windows does not support some special characters like 
<img width="176" alt="image" src="https://user-images.githubusercontent.com/25149022/191192151-759c003f-2348-4e90-b9de-ad1615ab5de9.png">

filter_filename function is problematic with other character encoding than English.

**Comment by felagund** [comment]
I am not on Windows (I am on Ubuntuú.

However, my filename does not have any illegal characters, Windows work with "í" in a filename perfectly right. Indeed it is problematic, probably it should e encoding aware. I know no php so cannot really offer help (and I already downlaoded the course I was interested in, thanks!).

**Comment by sumeetweb** [comment]
I think the issue is with this line 21 in filter_filename
`
$filename = mb_strcut(pathinfo($filename, PATHINFO_FILENAME), 0, 255 - ($ext ? strlen($ext) + 1 : 0), mb_detect_encoding($filename)) . ($ext ? '.' . $ext : '');
`

**Comment by felagund** [comment]
No, the problem really seems to be with the preg_replace.

Commenting out the line you suggested does not change enything. I inserted echo statemens after each functino in this function and it start coming out garbled after preg_replace already.

**Comment by sumeetweb** [comment]
Thanks. I'm removing the preg_replace for now.

**Comment by felagund** [comment]
Actually, per https://stackoverflow.com/questions/19629893/does-preg-replace-change-my-character-set

when `/u` is added to this line:

    [\x7F\xA0\xAD]|          # non-printing characters DEL, NO-BREAK SPACE, SOFT HYPHEN

so thdt it looks like this: 

    [\x7F\xA0\xAD]/u|          # non-printing characters DEL, NO-BREAK SPACE, SOFT HYPHEN

the problem is solved

**Comment by sumeetweb** [comment]
Added it to main. Thanks again, Tomas.
