### ISSUE TITLE
Not working for thinkific.com anymore?

### ISSUE THREAD

**Issue by ferngarc** [sumeetweb/Thinki-Downloader#30]
I tried recreating the steps and noticed there's no longer a php endpoint for the courses. Does this still work as of today? (10/20/2022) ?

**Comment by sumeetweb** [comment]
I will check it out and let you know, if it's still up or not.

**Comment by aaalex2** [comment]
Working like charm for me

**Comment by sumeetweb** [comment]
Thanks, @aaalex2 for checking it out.

**Comment by sumeetweb** [comment]
@ferngarc "php" is just a course slug, as I showed it in the video. 
Every course url is in the format "https://" + URL-OF-WEBSITE + "/api/course_player/v2/courses/" + COURSE_SLUG

**Comment by ferngarc** [comment]
Hmm... I think there's something else missing here because when I try this, it does parse the different classes and adds them to their own respective folders, but just downloads an empty directory with the lesson name. For example: 
```
cd 1.\ Introductory\ Video

1. Introductory Video]$ ls 
-alh
total 0
```

**Comment by ferngarc** [comment]
Here's an example of the script running. It definitely is parsing correctly, but skips the step where it actually downloads the video. 
```
THINKIFIC DOWNLOADER
Revision 6.1 ~ 14th March 2022
Author : SumeetWeb ~ https://github.com/sumeetweb
Consider buying me a coffee at : https://www.ko-fi.com/sumeet
Fetching Course Contents... Please Wait...
Downloading Introductory Video
Downloading Introduction to Glazes
Downloading Mixing Glazes
Downloading Printing to one page
Downloading Capturing Images
Downloading Geology
```

**Comment by sumeetweb** [comment]
Need to check the course json file for that. There might be changes to
video download link or might be some issues with php extensions.

**Comment by gytisgreitai** [comment]
yep, no Videos for me also :)

**Comment by sumeetweb** [comment]
Let me test it on hootsuite today.

> yep, no Videos for me also :)

**Comment by sumeetweb** [comment]
Videos are getting downloaded here.
![image](https://user-images.githubusercontent.com/25149022/202849536-093f603d-9127-4343-bf64-dd10beb4b5f0.png)

Can you try downloading the course with docker? It's in add-docker-support branch. Just set the env config and hit docker compose up.

For your reference, my .env file looks like this:
![image](https://user-images.githubusercontent.com/25149022/202849644-e9829baa-8cd0-4eed-8c6b-5e3c58fc9dc1.png)

Here's the repo:
[add-docker-support branch](https://github.com/sumeetweb/Thinki-Downloader/tree/add-docker-support)

**Comment by gytisgreitai** [comment]
hm but docker does not have anything "special" ? The command is just the same as I would launch from command line, at least what I see in compose.yaml file, and there are no code changes.

the problem is at this line:

https://github.com/sumeetweb/Thinki-Downloader/blob/300da1932c648d99cca2c3d0eec37155c50bc45a/include/downloader.functions.php#L90

For the new courses there is no more `Lesson` but rather `Iframe`:

```
{
      "id": 123,
      "position": 2,
      "chapter_id": 1234,
      "name": "Some Name",
      "contentable_type": "Iframe",
      "slug": "123-some-name",
      "is_free_trial": false,
      "next_content_id": 12345,
      "next_content_slug": "123456-some-other-name",
      "next_content_type": "Iframe",
      "display_name": "Multimedia",
      "contentable": 123123,
      "contentable_id": 12312312,
      "payment_required": false,
      "draft": false,
      "is_released": true,
      "release_date": null,
      "prerequisite": false,
      "total_post_count": 0,
      "discussions_enabled": false,
      "meta_data": null,
      "expand_enabled": false,
      "lesson_type_label": "VIDEO",
      "lesson_type_icon": "video",
      "default_lesson_type_label": "Multimedia",
      "default_lesson_type_icon": "multimedia",
      "under_construction": false
    }
```
So I naively tried to change the If, but the whole format seems to be different, cause changing the name would produce the link similar to this:

```
https://www.example.org/api/course_player/v2/lessons/123/download
```

but what we actually want is this:
```
 https://www.example.org/api/course_player/v2/iframes/123
```

The contents of the url is as following:
```
 {
    "iframe": {
        "id": 1230853,
        "source_url": "https://player.example.org/playb.html?vid=9876",
        "source_type": null
    }
}
````

Now if we look at the requests made it actually hits the following url with the same id (this is example: 9876) and there is also an account Id:
```
https://edge.api.brightcove.com/playback/v1/accounts/:account_id_here/videos/9876
```

Which returns a json similar to this:

```
{
  "poster": "<jpeg file>",
  "thumbnail": "<jpeg file>",
  "poster_sources": [
      {
          "src": "<jpeg file>"
      }
  ],
  "thumbnail_sources": [
      {
          "src": "<jpeg file>"
      }
  ],
  "description": null,
  "tags": [],
  "cue_points": [],
  "custom_fields": {},
  "account_id": ":account_id_here",
  "sources": [
      {
          "codecs": "avc1,mp4a",
          "ext_x_version": "4",
          "src": "http://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/:account_id_here/:long_uuuid_here/6s/master.m3u8?fastly_token=:token_here",
          "type": "application/x-mpegURL"
      },
      <....>
  ]
}
```

That master.m3u8 contains the video. The format of the master.m3u8:

```
EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-0",NAME="en (Dub)",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en",URI="http://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/:account_id_here/:uuid_here/:uuid_here/6s/rendition.m3u8?fastly_token=token_here"
<.....>
```

**Comment by sumeetweb** [comment]
Thanks for a detailed autopsy of it.

Yes, docker branch has no code changes, it's just same. For the content
type Iframe, it's not been implemented yet. In some courses, they used
htmlItem as content type for publishing embed videos which were saved
nicely as html.

For adding it, I need to get hold of an account for it and get a list of
content types that they provide.

Brightcove may be downloadable else we will use youtube dl to get the
streams and stitch it together for a mp4.

**Comment by sumeetweb** [comment]
I will add support for Iframes in upcoming weekends.

**Comment by gytisgreitai** [comment]
> Brightcove may be downloadable else we will use youtube dl to get the streams and stitch it together for a mp4.
> […](#)

yep, thanks for the hint, used yt-dlp, fetches everything nicely with subtitles. The only thing that puzzles me:
- where does the account_id come from, for now hardcoded one works
- `Accepts` header sent to `edge.api.brightcove.com` has some sort of signed key

**Comment by sumeetweb** [comment]
Going through a blog, found this :

![image](https://user-images.githubusercontent.com/25149022/202921850-e5cfcdcf-23ae-44cf-ad2c-8ef509ed2a08.png)


Sample JSON for reference : 
```
{
  "poster": "https://cf-images.us-east-1.prod.boltdns.net/v1/static/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/1bace563-1c4d-4617-90a3-600e0d48c0f1/960x540/match/image.jpg",
  "thumbnail": "https://cf-images.us-east-1.prod.boltdns.net/v1/static/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/86c305ad-5614-4ad7-a8b2-3cd49bcffca3/300x169/match/image.jpg",
  "poster_sources": [
    {
      "src": "https://cf-images.us-east-1.prod.boltdns.net/v1/static/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/1bace563-1c4d-4617-90a3-600e0d48c0f1/960x540/match/image.jpg"
    }
  ],
  "thumbnail_sources": [
    {
      "src": "https://cf-images.us-east-1.prod.boltdns.net/v1/static/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/86c305ad-5614-4ad7-a8b2-3cd49bcffca3/300x169/match/image.jpg"
    }
  ],
  "description": null,
  "tags": [
    "2017",
    "corporate marketing",
    "customer story"
  ],
  "cue_points": [],
  "custom_fields": {
    "businessunit": "Media",
    "producer": "BCI",
    "projectid": "1217"
  },
  "account_id": "1160438696001",
  "sources": [
    {
      "codecs": "avc1,mp4a",
      "ext_x_version": "4",
      "src": "http://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/10s/master.m3u8?fastly_token=NjM3YWQ3MDVfMzFmMmM4YzliNDExNWZiZDE3NjE5ODkxMTJkZDA4OTAwODNiMmE1YjY1ZDg2MWFiM2Q4ZjU1MmQ4MGRjMzRmZQ%3D%3D",
      "type": "application/x-mpegURL"
    },
    {
      "codecs": "avc1,mp4a",
      "ext_x_version": "4",
      "src": "https://manifest.prod.boltdns.net/manifest/v1/hls/v4/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/10s/master.m3u8?fastly_token=NjM3YWQ3MDVfMzFmMmM4YzliNDExNWZiZDE3NjE5ODkxMTJkZDA4OTAwODNiMmE1YjY1ZDg2MWFiM2Q4ZjU1MmQ4MGRjMzRmZQ%3D%3D",
      "type": "application/x-mpegURL"
    },
    {
      "codecs": "avc1,mp4a",
      "profiles": "urn:mpeg:dash:profile:isoff-live:2011",
      "src": "http://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/6s/manifest.mpd?fastly_token=NjM3YWQ3MDVfYjFlYmM4ZDdjYWM2MGViYzhjYjUzOWM3ZDQzNGEyMGMyYTIyZmI3MWI3ZWJmYTBmYjZiYjQwMDc5Y2U4NjBjYQ%3D%3D",
      "type": "application/dash+xml"
    },
    {
      "codecs": "avc1,mp4a",
      "profiles": "urn:mpeg:dash:profile:isoff-live:2011",
      "src": "https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/6s/manifest.mpd?fastly_token=NjM3YWQ3MDVfYjFlYmM4ZDdjYWM2MGViYzhjYjUzOWM3ZDQzNGEyMGMyYTIyZmI3MWI3ZWJmYTBmYjZiYjQwMDc5Y2U4NjBjYQ%3D%3D",
      "type": "application/dash+xml"
    },
    {
      "avg_bitrate": 3550000,
      "codec": "H264",
      "container": "MP4",
      "duration": 57258,
      "height": 1080,
      "size": 25420912,
      "src": "http://bcbolt446c5271-a.akamaihd.net/media/v1/pmp4/static/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/e7f924a0-17dd-4a05-8c08-19cc1786bcac/main.mp4?akamai_token=exp=1668994821~acl=/media/v1/pmp4/static/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/e7f924a0-17dd-4a05-8c08-19cc1786bcac/main.mp4*~hmac=5e5843fd31b9499938f8651d46fd02fc3fc8d6c73f3aa12cf025d7890524a486",
      "width": 1920
    },
    {
      "avg_bitrate": 3550000,
      "codec": "H264",
      "container": "MP4",
      "duration": 57258,
      "height": 1080,
      "size": 25420912,
      "src": "https://bcbolt446c5271-a.akamaihd.net/media/v1/pmp4/static/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/e7f924a0-17dd-4a05-8c08-19cc1786bcac/main.mp4?akamai_token=exp=1668994821~acl=/media/v1/pmp4/static/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/e7f924a0-17dd-4a05-8c08-19cc1786bcac/main.mp4*~hmac=5e5843fd31b9499938f8651d46fd02fc3fc8d6c73f3aa12cf025d7890524a486",
      "width": 1920
    },
    {
      "avg_bitrate": 2062000,
      "codec": "H264",
      "container": "MP4",
      "duration": 57258,
      "height": 720,
      "size": 14775165,
      "src": "http://bcbolt446c5271-a.akamaihd.net/media/v1/pmp4/static/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/37866c58-2bcd-4881-ae5c-34128298b314/main.mp4?akamai_token=exp=1668994821~acl=/media/v1/pmp4/static/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/37866c58-2bcd-4881-ae5c-34128298b314/main.mp4*~hmac=491c8b1c9c7c510046e6e15dacadaa4c78c065d9570914d7d71e0c87514d2f9a",
      "width": 1280
    },
    {
      "avg_bitrate": 2062000,
      "codec": "H264",
      "container": "MP4",
      "duration": 57258,
      "height": 720,
      "size": 14775165,
      "src": "https://bcbolt446c5271-a.akamaihd.net/media/v1/pmp4/static/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/37866c58-2bcd-4881-ae5c-34128298b314/main.mp4?akamai_token=exp=1668994821~acl=/media/v1/pmp4/static/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/37866c58-2bcd-4881-ae5c-34128298b314/main.mp4*~hmac=491c8b1c9c7c510046e6e15dacadaa4c78c065d9570914d7d71e0c87514d2f9a",
      "width": 1280
    }
  ],
  "name": "Video Marketing Helped Xero Attract, Retain and Grow to 1 Million Subscribers",
  "reference_id": "XERO-30-001",
  "long_description": null,
  "duration": 57259,
  "economics": "AD_SUPPORTED",
  "text_tracks": [
    {
      "id": "bf226bd9-59bc-489f-aa6e-8bf01573b014",
      "account_id": "1160438696001",
      "src": "http://bcbolt446c5271-a.akamaihd.net/media/v1/text/vtt/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/bf226bd9-59bc-489f-aa6e-8bf01573b014/text.vtt?akamai_token=exp=1668994821~acl=/media/v1/text/vtt/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/bf226bd9-59bc-489f-aa6e-8bf01573b014/text.vtt*~hmac=6b512120fbe9ce357cda0ec1279e86ef5f6ad65f78d344711fd2ee7ad48418ce",
      "srclang": "en",
      "label": "English",
      "kind": "captions",
      "mime_type": "text/webvtt",
      "asset_id": null,
      "sources": [
        {
          "src": "http://bcbolt446c5271-a.akamaihd.net/media/v1/text/vtt/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/bf226bd9-59bc-489f-aa6e-8bf01573b014/text.vtt?akamai_token=exp=1668994821~acl=/media/v1/text/vtt/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/bf226bd9-59bc-489f-aa6e-8bf01573b014/text.vtt*~hmac=6b512120fbe9ce357cda0ec1279e86ef5f6ad65f78d344711fd2ee7ad48418ce"
        },
        {
          "src": "https://bcbolt446c5271-a.akamaihd.net/media/v1/text/vtt/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/bf226bd9-59bc-489f-aa6e-8bf01573b014/text.vtt?akamai_token=exp=1668994821~acl=/media/v1/text/vtt/clear/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/bf226bd9-59bc-489f-aa6e-8bf01573b014/text.vtt*~hmac=6b512120fbe9ce357cda0ec1279e86ef5f6ad65f78d344711fd2ee7ad48418ce"
        }
      ],
      "in_band_metadata_track_dispatch_type": "",
      "default": false
    },
    {
      "id": null,
      "account_id": "1160438696001",
      "src": "http://manifest.prod.boltdns.net/thumbnail/v1/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/low-res/thumbnail.webvtt?fastly_token=NjM3YWQ3MDVfMDdlMzFmMDgyMjdiMDU2NWI3NTY0ZDU5YzNkM2JlMWNkZWVjMzA1MTIzYmUxMjk1YzEzMmY3MTFiMjdiOWQwNQ%3D%3D",
      "srclang": null,
      "label": "thumbnails",
      "kind": "metadata",
      "mime_type": "text/webvtt",
      "asset_id": null,
      "sources": null,
      "default": false,
      "width": 480,
      "height": 270
    },
    {
      "id": null,
      "account_id": "1160438696001",
      "src": "https://manifest.prod.boltdns.net/thumbnail/v1/1160438696001/7a1af3c8-ede6-484d-94ea-331b5fa83c60/low-res/thumbnail.webvtt?fastly_token=NjM3YWQ3MDVfMDdlMzFmMDgyMjdiMDU2NWI3NTY0ZDU5YzNkM2JlMWNkZWVjMzA1MTIzYmUxMjk1YzEzMmY3MTFiMjdiOWQwNQ%3D%3D",
      "srclang": null,
      "label": "thumbnails",
      "kind": "metadata",
      "mime_type": "text/webvtt",
      "asset_id": null,
      "sources": null,
      "default": false,
      "width": 480,
      "height": 270
    }
  ],
  "published_at": "2017-06-19T16:13:36.370Z",
  "created_at": "2017-06-19T16:13:36.370Z",
  "updated_at": "2021-05-18T14:11:49.067Z",
  "offline_enabled": false,
  "link": null,
  "id": "5476480570001",
  "ad_keys": null
}
```

**Comment by AndrewsCodeNZ** [comment]
Am also having some Thinkific problems. Script runs but doesn't download any files. 

THINKIFIC DOWNLOADER
Revision 6.1 ~ 14th March 2022
Author : SumeetWeb ~ https://github.com/sumeetweb

Consider buying me a coffee at : https://www.ko-fi.com/sumeet
Fetching Course Contents... Please Wait..

Running:
curl 7.81.0 (x86_64-pc-linux-gnu) 
PHP 7.4.33 (cli) (built: Nov  8 2022 11:33:53) ( NTS )
Ubuntu 22.04.1 LTS

I've worked before with you Sumeet on extending the codebase.

**Comment by sumeetweb** [comment]
> I've worked before with you Sumeet on extending the codebase.

Hi Andrew.

Can you check if the files that are not being downloaded are of type "MultiMedia"?

**Comment by AndrewsCodeNZ** [comment]
It doesn't appear to work for any types Sumeet. It's very strange. I also set-up a Windows box in case it was my Ubuntu config that was the problem and the exact same problem occurs. Will send you some credentials for you to try.

**Comment by sumeetweb** [comment]
https://github.com/sumeetweb/Thinki-Downloader/tree/multimedia-patch

Anyone facing this issue, please check if anything gets downloaded.

**Comment by AndrewsCodeNZ** [comment]
Sorry Sumeet, looks like it was a config issue – am unsure where exactly the issue was despite trying to find it. The strange thing was it was across both Windows and Ubuntu? Weird. I nuked both machines and did clean installs and both the main branch and multimedia-patch work perfectly! Thanks for your time helping me troubleshooting.

**Comment by ferngarc** [comment]
That's bizarre. I am running this on just a regular MacBook, I tried the patch branch and docker branch. Both returned empty lecture directories. I'll try running this in a terminal as opposed to running this on VSCODE? Not sure what else could be missing. 🤔

**Comment by AndrewsCodeNZ** [comment]
What version of PHP are you running @ferngarc ?

**Comment by ferngarc** [comment]
@AndrewsCodeNZ here's the output from terminal. 
```
*[multimedia-patch][~/git/Thinki-Downloader]$ php --version
PHP 8.1.11 (cli) (built: Sep 29 2022 19:44:28) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.11, Copyright (c), by Zend Technologies
```

I tried locally and with Docker too. Same results  😢

**Comment by AndrewsCodeNZ** [comment]
@ferngarc Will have a go on my Mac when I get home tonight and let you know how I go.

**Comment by AndrewsCodeNZ** [comment]
OK, script runs perfect on an out of the box macOS Big Sur install with PHP 7.3.29-to-be-removed-in-future-macOS (cli) (built: Aug 29 2022 08:54:14) ( NTS )

When I had my issues before I did have PHP 8.x installed on both boxes (I didn't RTFM) and then switched them back to 7.x which is what I think may have been the problem. 

Am not a macOS user so I don't know how difficult it is to switch to a 7.x version. When I have some more time I'll upgrade my Windows VM to 8.x and see if it breaks.

Has anyone else had it running on PHP 8.x?

**Comment by AndrewsCodeNZ** [comment]
@ferngarc What site is it you are accessing?

**Comment by ferngarc** [comment]
https://ceramicmaterialsworkshop.thinkific.com :D 

Currently studying the chemistry behind glazing for ceramics haha

**Comment by AndrewsCodeNZ** [comment]
Nice! 

They don't seem to have any free courses or preview lessons so I can't see what's happening video-wise. Everything else looks pretty much out-the-box Thinkific. 

You aren't getting a JSON file created I'm guessing?

**Comment by sumeetweb** [comment]
If there isn't a json file being generated, then issue might be with
config.

**Comment by STP404** [comment]
@ferngarc Did you get it working?
@sumeetweb I am also having an issue downloading the video files.

I tried the main branch as well as Docker and Multimedia, all with the same result.
I started with PHP 8 but went down to 7.4 to see if that was the issue, still get the same result. 
I am working on a PC. 

The code seems to be configured correctly, it launches, logs in, reads the course tree and start creating the folders on my harddrive and downloading... but it will download everything (PDF, Excel files, etc...) except for the videos. Where should be a video, instead it creates an html file with an iframe to the video.
The iframe also seems to be correct, it points to a Vimeo video, but seems it is private I can't see it on that page, it is only visible through the course website... https://player.vimeo.com/video/763596690?h=e022bc317e

Before I been using Youtube-DL to download courses when their video files ended on "/master.json?base64_init=1" but this specific course ends as "/master.json?query_string_ranges=1&base64_init=1"... in case that helps. 

Interestingly enough, when there is a public Youtube video it does the same, it gets included in the html file but it doesn't download the actual file...

Any advice on how to get the video files? Am I missing something?

**Comment by sumeetweb** [comment]
Hi there,

The script is working fine, if iframe html files are generated. If there's
no video files then, probably the course doesn't have videos directly added
on platform. The course site, I tested the script embedded wistia videos
and they were playing fine from iframes locally. For your course site, it's
vimeo and maybe their CORs prevent from playing in other places. In that
case, we can proxy the ifame loader with some sort of http server, with
origin header set as the course site.

Best,
Sumeet.

**Comment by ferngarc** [comment]
> @ferngarc Did you get it working? @sumeetweb I am also having an issue downloading the video files.
> 
> I started with PHP 8 but went down to 7.4 to see if that was the issue, still get the same result. I am working on a PC.
> 
> The code seems to be configured correctly, it launches, logs in, reads the course tree, creates the JSON, start creating the folders on my harddrive and downloading... but it will download everything (PDF, Excel files, etc...) except for the videos.
> 
> On the course pages where there is a video and some other files, it will download the other files but will skip the video. On the course pages where there is only a video and no other files, instead of downloading the video it creates an html file with an iframe to the video. The iframe also seems to be correct, it points to a Vimeo video, but seems it is private I can't see it on that page, it is only visible through the course website... https://player.vimeo.com/video/763596690?h=e022bc317e
> 
> Before I have been using Youtube-DL to download courses when their video files ended on "/master.json?base64_init=1" but this specific course ends as "/master.json?query_string_ranges=1&base64_init=1" But I have tried Thinki-Downloader also on those courses that download with Youtube-DL and the result is the same, gets everything except for the video files.
> 
> Interestingly enough, when there is a public Youtube video it does the same, it gets included in the html file but it doesn't download the actual file...
> 
> Any advice on how to get the video files? Am I missing something?
> 
> Ps. I tried the Multimedia branch running through Docker and I got the exact same result

Yep, describes my situation exactly.

**Comment by sumeetweb** [comment]
If video is added as an embed type, script thinks it as HtmlItem content type and save it as web page file instead of downloading video. As vimeo is similarly embed in page, it does thinks it as HtmlItem page and saves it. So, video doesn't get downloaded.

Video downloads is supported if content type is **Multimedia** and/or there's "**wistia**" video player in your course.

**Comment by FazalAAli** [comment]
Hi @sumeetweb, I'm having the same problem and can confirm that the videos are wistia videos yet the files downloaded are 0B. Can you please guide on how to get the wistia videos?
