### ISSUE TITLE
Enable Multi Threading for Multiple Urls simultaneously

### ISSUE THREAD

**Issue by aaalex2** [sumeetweb/Thinki-Downloader#31]
I Need to be Able to enter More than 1 url by time

**Comment by sumeetweb** [comment]
Multiple urls as multiple courses of same website?

If yes, then you can run the downloader script in another terminal.

**Comment by aaalex2** [comment]
with the same cookies?

**Comment by sumeetweb** [comment]
Yes, if you're on same website.
