### ISSUE TITLE
Change Filename with Foldername

### ISSUE THREAD

**Issue by CrackHub** [sumeetweb/Thinki-Downloader#32]
Hi, it is working good but mp4 files coming with random names (like; 908723987329.mp4)
Can we change this names with folder name?
When you download 50 videos it is really hard doing this manually.
Thanks.

**Comment by sumeetweb** [comment]
Hi, The video's name is fetched from the downloadable URL itself. It shouldn't fully contain numbers, though, it ends with numbers, Can you share some screenshot for the same to verify?

Thanks.
