### ISSUE TITLE
failing with silent exited 0

### ISSUE THREAD

**Issue by gauravrock** [sumeetweb/Thinki-Downloader#37]
Looks like the code is failing with silent exited 0, attaching the ss below
![image](https://user-images.githubusercontent.com/23530368/231986545-86d5afb9-e801-4f2c-81cb-1122892adb14.png)

the container is created successfully but the fetch is failed with silent exited 0. I checked the below code, not sure what is resulting in the failure😥
```
curl_setopt($process, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($process, CURLOPT_SSL_VERIFYHOST, 0);
```

**Comment by sumeetweb** [comment]
Duplicate https://github.com/sumeetweb/Thinki-Downloader/issues/7#issuecomment-862600074
