### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by Meesh977** [sumeetweb/Thinki-Downloader#38]
![image](https://github.com/sumeetweb/Thinki-Downloader/assets/96887795/bfefaed7-5ca6-4d91-9ba9-c8bab4ad9cdb)
 

after sorting everything out i still get "Authentication Error"

please help

**Comment by parkournick00110010** [comment]
:arrow_up:

**Comment by parkournick00110010** [comment]
Try to fill in the COOKIE_DATA correctly, in the video ( https://www.youtube.com/watch?v=RqaJkuTz_5g ) it was named "cookie" but in my browser the correct name was "set-cookie"

example of how it should be: https://github.com/sumeetweb/Thinki-Downloader/issues/30#issuecomment-1320869246
![image](https://github.com/sumeetweb/Thinki-Downloader/assets/131922314/80023938-78bf-402b-b79c-33b122cee09b)
