### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted?

### ISSUE THREAD

**Issue by rocnoa** [sumeetweb/Thinki-Downloader#4]
Great script, I followed your video instructions and ran it. I got the following error, however:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 67026976 bytes) in /Users/XXX/Documents/GitHub/Thinki-Downloader/thinkidownloader3.php on line 201

Is this something that is easily addressable?

**Comment by sumeetweb** [comment]
It looks like PHP ran out of memory. You should increase PHP's memory limit in PHP.INI file from 128M/256M to at least half of your system's memory (if it's 4GB RAM then 2GB) to 2GB or 3GB or even more. Your PHP Memory Limit should be greater than the size of video you are trying to download. 

By default in your php.ini file, the memory limit maybe 128M or 256M.
memory_limit = 256M
change it to
memory_limit = 2G
or
memory_limit = 3G
or a higher value until you don't get a memory size exhausted error.

The solution to this problem is chunked downloading through PHP. I have got some repos and figuring them out to solve this.

**Comment by rocnoa** [comment]
Thanks for the prompt reply.

Indeed, I got a memory size exhausted error. The course is such that it has 3 2+ hour videos in it.

I got Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130023456 bytes) in /Users/XXX/Documents/GitHub/Thinki-Downloader/thinkidownloader3.php on line 201

Looking forward to an eventual update. Good job so far, @sumeetweb

**Comment by rocnoa** [comment]
I modified php.ini memory_limit to 2G, 4G, 6G and at the end to -1.

Even with -1 I got:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 99442720 bytes) in /Users/obretenov/Documents/GitHub/Thinki-Downloader/thinkidownloader3.php on line 201

Could this be for another reason or does this mean I should just look forward to an eventual chunked downloading update?

**Comment by rocnoa** [comment]
I modified php.ini memory_limit to 2G, 4G, 6G and at the end to -1.

Even with -1 I got:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 99442720 bytes) in /Users/XXX/Documents/GitHub/Thinki-Downloader/thinkidownloader3.php on line 201

Could this be for another reason or does this mean I should just look forward to an eventual chunked downloading update?

**Comment by sumeetweb** [comment]
Maybe the video size is going high. Can you find the length of the largest video in the course?

**Comment by rocnoa** [comment]
The largest one so far is 2 hours, 7 minutes, and 44 seconds.

**Comment by sumeetweb** [comment]
Hello @kiseta I have now implemented the chunked downloading thing in the script. I will push it in the repo soon.

**Comment by sumeetweb** [comment]
For downloading PDFs and other materials, I need a account which has those downloadable things in course to implement it in script.

**Comment by sumeetweb** [comment]
> Hello @kiseta I have now implemented the chunked downloading thing in the script. I will push it in the repo soon.

@rocnoa Memory limit exhausted has been fixed now.
