### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by akvcs91** [sumeetweb/Thinki-Downloader#45]
```
THINKIFIC DOWNLOADER
Revision 6.2 ~ 3rd March 2023
Author : SumeetWeb ~ https://github.com/sumeetweb
Consider buying me a coffee at : https://www.ko-fi.com/sumeet
Thinki-Parser Experimental is available for testing!
----------------------------------------------------------
Authentication Error
```

I have edited config.php as presented in video tutorial.

**Comment by sumeetweb** [comment]
It happens if, the user session is logged out. Try generating the token again.

**Comment by grtdysmal** [comment]
I am getting the Authentication error as well. I tried on 2 different course on the site, and I even signed out and signed back in again to see if that helped. I tried multiple attempts, making sure that the cookie data was copied correctly and everything. I am using the docker method on Windows 11. What should I try next?
