### ISSUE TITLE
videos are not getting downloaded

### ISSUE THREAD

**Issue by atharvabb** [sumeetweb/Thinki-Downloader#46]

**Comment by atharvabb** [comment]
as soon as video is encountered download process stops and further things are also skipped
![image](https://github.com/sumeetweb/Thinki-Downloader/assets/74582401/d84cdce5-ffab-4f8a-bba2-87c416a3c093)

**Comment by sumeetweb** [comment]
Is the videos in the course page is of embedded type like streams coming from vimeo? Then, it might does not support.

**Comment by momceras** [comment]
Same problema and the video is not on vimeo

**Comment by ER-95** [comment]
@sumeetweb Was there ever any movement on this? Trying to download a free course, but it just stops straight away.

**Comment by momceras** [comment]
I could comment on the code inside downloader.functions.php

*/**




*     fdownload($sendurl, $vname);                    // save page content
along with the Video                    $html_fileName = $vname . ".html";
                  file_put_contents($html_fileName,
$temp["lesson"]["html_text"]); */*

and everything else went well.
You can try to fix that if you want.

ER ***@***.***> escreveu no dia quinta, 21/09/2023 à(s) 12:31:

**Comment by ER-95** [comment]
@momceras That just makes the script terminate straight away for me:
![image](https://github.com/sumeetweb/Thinki-Downloader/assets/53078703/f8a90cba-d797-4be8-91d7-24b4c9508ccd)

**Comment by momceras** [comment]
I do not use a path on thinkidownloader3.php
php thinkidownloader3.php httpt://...

did you try without that path ?

ER ***@***.***> escreveu no dia quinta, 21/09/2023 à(s) 15:00:

**Comment by ER-95** [comment]
@momceras I'm calling a specific directory; if I were to do it that way it wouldn't run at all

**Comment by momceras** [comment]
something like  pathof\php.exe thinkidownloader.php https://(..) works for
me

ER ***@***.***> escreveu no dia quinta, 21/09/2023 à(s) 16:08:

**Comment by sumeetweb** [comment]
Hi there. Please try going with the docker method once and let me know if it works or not.

**Comment by gabyavra** [comment]
At least on wistia.com didn't work in Docker either. It downloads the html but not the videos. Also, if there are other links in the html, they don't seem to appear.

**Comment by Heph-Akin** [comment]
I had the same issue with the HTML downloading but none of the videos. Here's a link to a free course on the platform with some of their videos on wistia: https://www.hackdentistry.com/courses/take/free-sample-content/texts/44835495-viral-infection-hiv-structure-pathogenesis-video

**Comment by sumeetweb** [comment]
Thanks. I will look into it.

**Comment by sumeetweb** [comment]
Linking similar issues. #47 #48 #49
