### ISSUE TITLE
Docker-compose up -d

### ISSUE THREAD

**Issue by lbarria77** [sumeetweb/Thinki-Downloader#47]
Hello how are You, excelente script but once the .env is configured and docker compose is executed, it acts as if it were downloading, but when I check the folder it creates two files, one of type file and one html but both with 0KB

**Comment by sumeetweb** [comment]
Hello @lbarria77. Are the videos hosted on wistia?

**Comment by lbarria77** [comment]
@sumeetweb no there are un other platform based in thinkfic

**Comment by lbarria77** [comment]
Yes there are in westia @sumeetweb
