### ISSUE TITLE
Pull complete but can't fetch course contents?

### ISSUE THREAD

**Issue by g33khubber** [sumeetweb/Thinki-Downloader#49]
as per screenshot - any idea why?

![image](https://github.com/sumeetweb/Thinki-Downloader/assets/48877307/cdfa72a5-2a3b-42bd-9eae-f5ee67267b38)

**Comment by sumeetweb** [comment]
Hello. Are the videos hosted on wistia?

**Comment by g33khubber** [comment]
that's right.q
