### ISSUE TITLE
Empty URL, empty files..

### ISSUE THREAD

**Issue by bmbm1107** [sumeetweb/Thinki-Downloader#54]
The resulting files are empty, as in the case of issues related to wistia support.

![image](https://github.com/sumeetweb/Thinki-Downloader/assets/59874027/78b09199-7c07-4081-82a6-6daec8e0fb6f)

If i guess correctly, the problem is that $full_hd_url has no value.

![image](https://github.com/sumeetweb/Thinki-Downloader/assets/59874027/dde64d2f-8741-4277-af5f-a5568d66a718)

**Comment by sumeetweb** [comment]
Can you try once using v6.2.

https://github.com/sumeetweb/Thinki-Downloader/releases/tag/v3-rev-6.2

**Comment by bmbm1107** [comment]
Same results with v6.2

**Comment by sumeetweb** [comment]
I would need the lesson info to debug. Can you look for "lessons" in Chrome
Developer Tools > Network tab.

**Comment by bmbm1107** [comment]
Of course! Can you tell me in a little more detail what I'm looking for?

**Comment by bmbm1107** [comment]
is this what we are looking for?

`{"lesson":{"id":19067828,"video_id":9430896,"downloadable":false,"autoplay":false,"download_url":null,"html_text":null,"attachment_ids":[],"download_file_ids":[]},"attachments":[],"download_files":[],"videos":[{"id":9430896,"storage_location":"videoproxy","identifier":"ci43lcsjg8cj54ocb0r0","primary_thumbnail_url":"https://embed-ssl.wistia.com/deliveries/6f8676db21f33e462d27f93f3a361ccf37a24ba9.jpg","encoded_state":"finished"}]}`

**Comment by sumeetweb** [comment]
Thanks. I will look into it.

**Comment by sumeetweb** [comment]
Hi there, Can you test fix-lesson-dl branch?

https://github.com/sumeetweb/Thinki-Downloader/tree/fix-lesson-dl

**Comment by sumeetweb** [comment]
Merged to main,

**Comment by bmbm1107** [comment]
unfortunately the problem still persists

**Comment by bmbm1107** [comment]
on the other hand, feat/dl-percent branch is working for me.

**Comment by sumeetweb** [comment]
Can you share the lessons api response?

**Comment by bmbm1107** [comment]
perhaps part of the problem was that the lessons did not have "make this lesson downloadable" set on the admin interface. I set this up and now it works, but only in the branch mentioned above

`{"lesson":{"id":7114635,"video_id":1149220,"downloadable":true,"autoplay":true,"download_url":"/api/course_player/v2/lessons/7114635/download","html_text":null,"attachment_ids":[],"download_file_ids":[]},"attachments":[],"download_files":[],"videos":[{"id":1149220,"storage_location":"videoproxy","identifier":"bh52cj5fn27763maeur0","primary_thumbnail_url":"https://embed-ssl.wistia.com/deliveries/d750e4a7b86c404cdbde5aeeb932c63e5de04dcf.jpg","encoded_state":"finished"}]}`

**Comment by sumeetweb** [comment]
Thanks. I found an issue for lesson downloads. It was using url instead of video identifier. I fixed and
