### ISSUE TITLE
"Cookie data and Client Date not set. Use the ReadMe file first before using this script."

### ISSUE THREAD

**Issue by simplo** [sumeetweb/Thinki-Downloader#57]
Hi there, I get this error (on docker) even all the fields are compiled as it says on the video.
Can you please help me?

**Comment by sumeetweb** [comment]
Did you modified and saved the .env file as it is shown in the video?

**Comment by simplo** [comment]
Hi Sumeet, thanks for the fast reply.
I think it is all compiled and saved, as you can see in the acched
screenshot.
Can you please help me to understand what I'm doing wrong?

Thank you!
Simone

On Tue, 19 Dec 2023 20:20:34 -0800
Sumeet Naik ***@***.***> wrote:

> Did you modified and saved the .env file as it is shown in the video?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/sumeetweb/Thinki-Downloader/issues/57#issuecomment-1863822927
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

   *********************************
     Simone "Simplo" Murtas
           www.amartist.it
   *********************************

**Comment by simplo** [comment]
![Immagine](https://github.com/sumeetweb/Thinki-Downloader/assets/736206/8f1e3703-88b5-4d32-b1e2-6bd6bf11c34b)

**Comment by simplo** [comment]
![Immagine](https://github.com/sumeetweb/Thinki-Downloader/assets/736206/c31829b0-54c9-4671-9cce-18da9a719bea)

**Comment by sumeetweb** [comment]
Your might be running docker compose in different location.

**Comment by simplo** [comment]
I'm launching the command "docker-compose -f compose.selective.yaml up"
in the same folder where the .dev is, the root of the project.
![Immagine2](https://github.com/sumeetweb/Thinki-Downloader/assets/736206/8a34bb9e-268d-4b4e-af02-df949803cc38)

**Comment by sumeetweb** [comment]
You sre running selective downloads, but course data file is not there in the directory. Try running only docker compose up.

**Comment by simplo** [comment]
Same result, I'm totally new to Docker, mayb
![Immagine3](https://github.com/sumeetweb/Thinki-Downloader/assets/736206/8c9c1db2-e855-4f29-9e5c-958b5b8495db)
e I'm doing something wrong... :(

**Comment by sumeetweb** [comment]
Try running on a different directory. Docker maynot have access to the
.env file.

**Comment by simplo** [comment]
In the Docket Container I can see the .dev correctly compiled, is it right?
What do you mean? Have I to reinstall the github project on a different directory?
![Uploading Immagine4.png…]()

**Comment by simplo** [comment]
I reinstalled the github project on a new folder and now it is working!
Thank you so much!!!!

**Comment by sumeetweb** [comment]
Glad to help!
