### ISSUE TITLE
I can't get this to run for me

### ISSUE THREAD

**Issue by gamerchris360** [sumeetweb/Thinki-Downloader#6]
I have a fresh php 8.0.6 binary, uncommented the curl and mbstring values and I can't get this to work for me. Can you maybe help me? This is my output every time:

THINKIFIC DOWNLOADER
v3 ~ 7th January 2021
Author : SumeetWeb ~ https://github.com/sumeetweb
Fetching Course Contents... Please Wait...
Starting Download...

No folders created, nothing downloaded. I've been banging my head on this for 2 hours and am about ready to give up. It's a paid course and I can email you my values, but I get the same issue when trying to go to packt and get the Python workshop, so I think the problem might be my PHP/curl somewhere and not in the way I'm doing this. I appreciate any help you are willing to give.

**Comment by momceras** [comment]
Same thing happening to me.

**Comment by gamerchris360** [comment]
> Same thing happening to me.

My workaround for now is TubeDigger. Not quite as automated, but you can use it to grab videos one by one.

**Comment by sumeetweb** [comment]
Can you try this and re-run the script?

https://github.com/sumeetweb/Thinki-Downloader/issues/5#issuecomment-828128855

**Comment by momceras** [comment]
Thank you for the help.
I have tried several things by now:
Curl and mbstring  are enable but curl inside query function is returning false. Pasting the given url on browser, json string is returned.

I have tried to paste all data several times without success.
Any other hint ?

Best regards

**Comment by sumeetweb** [comment]
Can you confirm if cookie data has been added in the script?

**Comment by sumeetweb** [comment]
@gamerchris360 I will make a video soon to resolve all issues with downloader soon.

Best,
Sumeet.
