### ISSUE TITLE
program exit with code 0 with no explanation 

### ISSUE THREAD

**Issue by sator86** [sumeetweb/Thinki-Downloader#63]
Hello dear,
as you can see on the screen, the program exit by itself with code 0
no other error
can you please help
thank you

root@debian:~/Thinki-Downloader-main# docker-compose up 
Starting ThinkiDownloader ... done
Attaching to ThinkiDownloader
ThinkiDownloader    | THINKIFIC DOWNLOADER
ThinkiDownloader    | Revision 6.3.4 ~ 1st May 2024
ThinkiDownloader    | Author : SumeetWeb ~ https://github.com/sumeetweb
ThinkiDownloader    | Consider buying me a coffee at : https://www.ko-fi.com/sumeet
ThinkiDownloader    | Want to download only selected videos? Thinki-Parser is available! : https://sumeetweb.github.io/Thinki-Parser/
ThinkiDownloader    | ----------------------------------------------------------
ThinkiDownloader    | Fetching Course Contents... Please Wait...
ThinkiDownloader exited with code 0

![Capture d’écran 2024-06-03 à 15 50 01](https://github.com/sumeetweb/Thinki-Downloader/assets/55639966/6a53dca7-561b-4671-bbb7-0f8fcab4c497)

**Comment by sumeetweb** [comment]
Hi @sator86. The course link used in config is wrong. 

Search for below format in the browser dev tools.

https://URL-OF-WEBSITE/api/course_player/v2/courses/COURSE-NAME-SLUG

**Comment by sumeetweb** [comment]
Oh. You can try looking for loom videos downloader.

**Comment by sator86** [comment]
Hello,
I found some link to download from loom with share ID, but some links are private, do you have any idea how to download them ?

I can access from my browser, but not from a tool, below link example 
thank you


link example of private link : https://www.loom.com/embed/070a8e66c09d4f4985c665462408a6bc?sid=96f5a247-0180-4c27-8d3c-4e2bbf682742

link example of downloadable link 
https://www.loom.com/share/070a8e66c09d4f4985c665462408a6bc?sid=96f5a247-0180-4c27-8d3c-4e2bbf682742
