### ISSUE TITLE
Curl returning false

### ISSUE THREAD

**Issue by momceras** [sumeetweb/Thinki-Downloader#7]
I have playing around with this script to get it working, but no luck until now.
The curl is returning false and it is enabled on php.ini.
If I place the url, the json is properly returned.
Is the script working by now ?
Best regards

**Comment by momceras** [comment]
It looks like a self signed certificate problem. I'll check for more info

**Comment by momceras** [comment]
this fixed the problem until the next error:
`curl_setopt($process, CURLOPT_SSL_VERIFYPEER, false);`

Now getting another error:
PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in C:\inetpub\wwwroot\curso\thinkidownloader3.php:271
Stack trace:
#0 C:\inetpub\wwwroot\curso\thinkidownloader3.php(271): fwrite(false, '<div class="fr-...')
#1 C:\inetpub\wwwroot\curso\thinkidownloader3.php(243): chapterwise_download(Array)
#2 C:\inetpub\wwwroot\curso\thinkidownloader3.php(231): create_chap_folder(Array)
#3 C:\inetpub\wwwroot\curso\thinkidownloader3.php(330): init_course(Array)
#4 {main}
  thrown in C:\inetpub\wwwroot\curso\thinkidownloader3.php on line 271

Fatal error: Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in C:\inetpub\wwwroot\curso\thinkidownloader3.php:271
Stack trace:
#0 C:\inetpub\wwwroot\curso\thinkidownloader3.php(271): fwrite(false, '<div class="fr-...')
#1 C:\inetpub\wwwroot\curso\thinkidownloader3.php(243): chapterwise_download(Array)
#2 C:\inetpub\wwwroot\curso\thinkidownloader3.php(231): create_chap_folder(Array)
#3 C:\inetpub\wwwroot\curso\thinkidownloader3.php(330): init_course(Array)
#4 {main}
  thrown in C:\inetpub\wwwroot\curso\thinkidownloader3.php on line 271

**Comment by sumeetweb** [comment]
What is the language in your returned json? If it is not in English US/UK it will not download. you need to manually change a variable according to your native language.

**Comment by momceras** [comment]
Language is PT-pt. Where shoul I change ?
It seams something like a chars problem (ç,ã,õ...)

**Comment by momceras** [comment]
If you are saying this:
`if($content["contentable_type"] == "HtmlItem" && $content["display_name"] == "Texto") `

It is in english (text/video), but the folder names contains special chars as indicated.

**Comment by sumeetweb** [comment]
Can you send the json part?

**Comment by momceras** [comment]
> Can you send the json part?

[https://jpst.it/2xmHa]

**Comment by sumeetweb** [comment]
Problem is in query function. It maybe due to mbstring extension. Can you try to re-run the script with the new pushed code. I have fixed a memory exhausted bug. Please check.

**Comment by sumeetweb** [comment]
FYI mbstring extension is disabled by default in php.ini.

**Comment by momceras** [comment]
I had already enabled mbstring.
I will try with last code.

**Comment by sumeetweb** [comment]
Send me your php.ini file and php version you are using.

**Comment by momceras** [comment]
I have changed some code and I can get the text files but not the video (with the old version of the script)

In the new version I get only this:

`THINKIFIC DOWNLOADER
v3.1 ~ 14th June 2021
Author : SumeetWeb ~ https://github.com/sumeetweb
Consider buying me a coffee at : https://www.buymeacoffee.com/sumeet
Fetching Course Contents... Please Wait...`

Using 
PHP 8.0.0 (cli) (built: Nov 24 2020 22:02:58) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies


[PHP.INI](https://jpst.it/2xrmr)

**Comment by momceras** [comment]
$course_name is empty, in my case, inside function init_course.

this is the $datas variable content:

[$datas](https://jpst.it/2xtwE)

**Comment by sumeetweb** [comment]
> $course_name is empty, in my case, inside function init_course.
> 
> this is the $datas variable content:
> 
> [$datas](https://jpst.it/2xtwE)
Not empty. datas is subset of this. https://justpaste.it/9n66v
I'm not able to figure out if it's php 8 issue or something else. In the main file, thinkidownloader3.php turn error_reporting(0) to 1 and see what it prints in console. 
Try installing [laragon frome here.](https://github.com/leokhoa/laragon/releases/download/5.0.0/laragon-wamp.exe)
Here;s the php.ini : https://del.dog/raw/phpini

Best,
Sumeet

**Comment by momceras** [comment]
I added this code below `$return = curl_exec($process);` inside query function

```
if (curl_error($process)<>''){
	echo PHP_EOL.'________________Controle de erro'.PHP_EOL;
	var_dump(curl_error($process));
	echo PHP_EOL.'________________Fim Controle de erro'.PHP_EOL;}
```

It seams that something is messing with it :)

It returns 
```
________________Controle de erro
string(27) "Could not resolve host: api"

________________Fim Controle de erro
```


With the flag on 1

`PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in C:\inetpub\wwwroot\curso\include\downloader.functions.php:54
Stack trace:
#0 C:\inetpub\wwwroot\curso\include\downloader.functions.php(54): fwrite(false, '')
#1 C:\inetpub\wwwroot\curso\include\downloader.functions.php(26): chapterwise_download(Array)
#2 C:\inetpub\wwwroot\curso\include\downloader.functions.php(14): create_chap_folder(Array)
#3 C:\inetpub\wwwroot\curso\thinkidownloader3.php(21): init_course(Array)
#4 {main}
  thrown in C:\inetpub\wwwroot\curso\include\downloader.functions.php on line 54

Fatal error: Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in C:\inetpub\wwwroot\curso\include\downloader.functions.php:54
Stack trace:
#0 C:\inetpub\wwwroot\curso\include\downloader.functions.php(54): fwrite(false, '')
#1 C:\inetpub\wwwroot\curso\include\downloader.functions.php(26): chapterwise_download(Array)
#2 C:\inetpub\wwwroot\curso\include\downloader.functions.php(14): create_chap_folder(Array)
#3 C:\inetpub\wwwroot\curso\thinkidownloader3.php(21): init_course(Array)
#4 {main}
  thrown in C:\inetpub\wwwroot\curso\include\downloader.functions.php on line 54`

**Comment by sumeetweb** [comment]
> I added this code below `$return = curl_exec($process);` inside query function
> 
> ```
> if (curl_error($process)<>''){
> 	echo PHP_EOL.'________________Controle de erro'.PHP_EOL;
> 	var_dump(curl_error($process));
> 	echo PHP_EOL.'________________Fim Controle de erro'.PHP_EOL;}
> ```
> 
> It seams that something is messing with it :)
> 
> It returns
> 
> ```
> ________________Controle de erro
> string(27) "Could not resolve host: api"
> 
> ________________Fim Controle de erro
> ```
> 
> With the flag on 1
> 
> `PHP Fatal error: Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in C:\inetpub\wwwroot\curso\include\downloader.functions.php:54
> Stack trace:
> #0 C:\inetpub\wwwroot\curso\include\downloader.functions.php(54): fwrite(false, '')
> #1 C:\inetpub\wwwroot\curso\include\downloader.functions.php(26): chapterwise_download(Array)
> #2 C:\inetpub\wwwroot\curso\include\downloader.functions.php(14): create_chap_folder(Array)
> #3 C:\inetpub\wwwroot\curso\thinkidownloader3.php(21): init_course(Array)
> #4 {main}
> thrown in C:\inetpub\wwwroot\curso\include\downloader.functions.php on line 54
> 
> Fatal error: Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in C:\inetpub\wwwroot\curso\include\downloader.functions.php:54
> Stack trace:
> #0 C:\inetpub\wwwroot\curso\include\downloader.functions.php(54): fwrite(false, '')
> #1 C:\inetpub\wwwroot\curso\include\downloader.functions.php(26): chapterwise_download(Array)
> #2 C:\inetpub\wwwroot\curso\include\downloader.functions.php(14): create_chap_folder(Array)
> #3 C:\inetpub\wwwroot\curso\thinkidownloader3.php(21): init_course(Array)
> #4 {main}
> thrown in C:\inetpub\wwwroot\curso\include\downloader.functions.php on line 54`

Check this one:
https://stackoverflow.com/questions/1341644/curl-and-https-cannot-resolve-host

This says there's might be problem with your Network DNS or your curl.

**Comment by momceras** [comment]
I thin the problem is the URL passed to query function that is invalid
I checked and it gets `https:///api/course_player/v2/html_items/5217397` as parameter. So /// it's wrong

**Comment by momceras** [comment]
Ok, I'll give up and save video one by one.
Best regards

**Comment by sumeetweb** [comment]
> Ok, I'll give up and save video one by one.
> Best regards

I got it. Sorry, I forgot to rename a variable while restructuring codebase. It's just renaming of a file in download functions. I will push new one soon.

Never give up! 🥇 

Best,
Sumeet
