### ISSUE TITLE
Videos not downloading and no error reporting

### ISSUE THREAD

**Issue by tomforti** [sumeetweb/Thinki-Downloader#9]
When I run the PHP script I get that the please wait message and then it ends the script. Even if if enable error reporting it returns nothing.  Below is that it looks like including having error reporting on. I tried with PHP7 as well as PHP8 

`
C:\video>php thinkidownloader3.php https://courses.practicalpocus.com/api/course_player/v2/courses/POCUS
THINKIFIC DOWNLOADER
v3.1 ~ 14th June 2021
Author : SumeetWeb ~ https://github.com/sumeetweb
Consider buying me a coffee at : https://www.buymeacoffee.com/sumeet
Fetching Course Contents... Please Wait...

C:\video>
`

**Comment by sumeetweb** [comment]
https://github.com/sumeetweb/Thinki-Downloader/issues/5

Hello Tom,
This might be an issue with your curl or with the returned course data which may not be in english. Follow up on curl first with error_reporting to 1 and check anything gets log into console or not.

Best,
Sumeet
